<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>

    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-All</AnalysisLevel>
    <AnalysisMode>All</AnalysisMode>

    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup>
    <MinVerDefaultPreReleaseIdentifiers>preview.0</MinVerDefaultPreReleaseIdentifiers>
    <MinVerTagPrefix>v</MinVerTagPrefix>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="$(IsPackable) == 'true' And $(IsTestProject) != 'true'">
    <PackageReference Include="MinVer" PrivateAssets="all" />
  </ItemGroup>

  <PropertyGroup Condition="$(IsPackable) == 'true' And $(IsTestProject) != 'true'">
    <Authors>Robin L. Velte</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageProjectUrl>https://github.com/rlvelte/dotbahn</PackageProjectUrl>
    <RepositoryUrl>https://github.com/rlvelte/dotbahn</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>db;bahn;client;deutschebahn;api</PackageTags>
    <PackageIcon>Icon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup Condition="$(IsPackable) == 'true' And $(IsTestProject) != 'true'">
    <None Include="$(MSBuildThisFileDirectory)docs/images/logo-512x512.png" Pack="True" PackagePath="Icon.png" />
  </ItemGroup>

</Project>
