<?xml version='1.0' encoding='utf-8'?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Spectre.Console" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../source/DotBahn.Shared/DotBahn.Shared.csproj" />
    <ProjectReference Include="../../source/DotBahn.Stations/DotBahn.Stations.csproj" />
    <ProjectReference Include="../../source/DotBahn.Facilities/DotBahn.Facilities.csproj" />
    <ProjectReference Include="../../source/DotBahn.Modules/DotBahn.Modules.Authorization/DotBahn.Modules.Authorization.csproj" />
  </ItemGroup>
</Project>
